{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-observability.secretName" . }}
  labels:
    {{- include "llm-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.secrets.data.geminiApiKey | quote }}
  SPRING_R2DBC_USERNAME: {{ .Values.secrets.data.postgresUsername | quote }}
  SPRING_R2DBC_PASSWORD: {{ .Values.secrets.data.postgresPassword | quote }}
  SPRING_FLYWAY_USER: {{ .Values.secrets.data.postgresUsername | quote }}
  SPRING_FLYWAY_PASSWORD: {{ .Values.secrets.data.postgresPassword | quote }}
  CLICKHOUSE_USERNAME: {{ .Values.secrets.data.clickhouseUsername | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.secrets.data.clickhousePassword | quote }}
  KAFKA_USERNAME: {{ .Values.secrets.data.kafkaUsername | quote }}
  KAFKA_PASSWORD: {{ .Values.secrets.data.kafkaPassword | quote }}
  REDIS_PASSWORD: {{ .Values.secrets.data.redisPassword | quote }}
{{- end }}
